language: node_js
node_js:
  - lts/argon
  - lts/boron
  - stable
cache:
  directories:
    - node_modules
after_success:
  - npm i -g codecov
  - codecov --disable=gcov --file=coverage/coverage-final.json
